// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TplDemo.Model.Context;

namespace TplDemo.Model.Migrations
{
    [DbContext(typeof(MSSQLContext))]
    [Migration("20200628020923_insert-usermodule")]
    partial class insertusermodule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TplDemo.Model.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birth")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("IP")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("TplDemo.Model.Models.UserModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desc")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("MId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sequence")
                        .HasColumnType("varchar(36))");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserModule");
                });

            modelBuilder.Entity("TplDemo.Model.Models.UserModuleRel", b =>
                {
                    b.Property<string>("UMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("MId")
                        .HasColumnType("int");

                    b.Property<int>("RId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("UMID");

                    b.HasIndex("MId");

                    b.HasIndex("RId");

                    b.ToTable("UserModuleRel");
                });

            modelBuilder.Entity("TplDemo.Model.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("TplDemo.Model.Models.UserRoleRel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleRel");
                });

            modelBuilder.Entity("TplDemo.Model.Models.UserModuleRel", b =>
                {
                    b.HasOne("TplDemo.Model.Models.UserModule", "UserModule")
                        .WithMany("UserModuleRel")
                        .HasForeignKey("MId")
                        .HasConstraintName("FK_Module_Role_MId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TplDemo.Model.Models.UserRole", "UserRole")
                        .WithMany("UserModuleRel")
                        .HasForeignKey("RId")
                        .HasConstraintName("FK_Role_Module_RId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TplDemo.Model.Models.UserRoleRel", b =>
                {
                    b.HasOne("TplDemo.Model.Models.UserRole", "UserRole")
                        .WithMany("UserRoleRel")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Role_UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TplDemo.Model.Models.UserInfo", "UserInfo")
                        .WithMany("UserRoleRel")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserId_Role")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
